### ISSUE TITLE
change request url when selected "show other networks" option

### ISSUE THREAD

**Issue by success-together** [success-together/theconversation.social-extension#1]
Just add &social_networks=twitter /all based on checkbox in api call.

**Comment by success-together** [comment]
for only twitter, maybe url will be like this: https://theconversation.social/social_curation/?url=https://www.bbc.com/news/world-europe-65841666&social_networks=twitter
if checked the option, url is https://theconversation.social/social_curation/?url=https://www.bbc.com/news/world-europe-65841666&social_networks=all

**Comment by success-together** [comment]
updated the url.

**Comment by VirusNinja1210** [comment]
url?
